mail_signup: //mc.us3.list-manage.com/signup-form/subscribe?u=a681a4090bf81b76cf94816e9&amp;id=005e9de1f0
contact_action: https://getsimpleform.com/messages?form_api_token=76f65a452af3841b8e17691cc589d2b4
twitter: https://twitter.com
facebook: https://www.facebook.com
instagram: https://instagram.com
wattpad: https://www.wattpad.com